-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pizza_doce` VARCHAR(255) NOT NULL,
  `pizza_salgada` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- Seleção da tabela
SELECT * FROM tb_categorias;

-- Inserindo dados na tabela tb_categorias
INSERT INTO tb_categorias (pizza_doce, pizza_salgada)
VALUE ("Prime doce", "Prime salgada");

INSERT INTO tb_categorias (pizza_doce, pizza_salgada)
VALUE ("Alacarte doce", "Alacarte salgada");

INSERT INTO tb_categorias (pizza_doce, pizza_salgada)
VALUE ("Elite doce", "Elite salgada");

INSERT INTO tb_categorias (pizza_doce, pizza_salgada)
VALUE ("Padrão doce", "Padrão salgada");

INSERT INTO tb_categorias (pizza_doce, pizza_salgada)
VALUE ("Especial doce", "Especial salgada");

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizzas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `sabor` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `preco` DECIMAL(4,2) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pizzas_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizzas_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_pizzaria_legal`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Seleção da tabela tb_pizzas
SELECT * FROM tb_pizzas;

-- Inserindo dados na tabela tb_pizzas
INSERT INTO tb_pizzas (sabor, nome, preco, tipo, tb_categorias_id)
VALUE ("Portugesa", "PortalPrime", 78.99, "Grande", 1);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo,  tb_categorias_id)
VALUE ("Portugesa", "PortalPadrão", 32.99, "Grande", 4);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo,  tb_categorias_id)
VALUE ("Portumarão", "PortalEspecial", 51.50, "Grande", 5);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo,  tb_categorias_id)
VALUE ("Portumarão", "PortalEspecial", 28.64, "Broto", 5);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo,  tb_categorias_id)
VALUE ("Calabresa", "Calacarte", 25.00, "Grande", 2);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo, tb_categorias_id)
VALUE ("Calabresa", "Calaelite", 35.50, "Grande", 3);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo,  tb_categorias_id)
VALUE ("Brigadeiro", "BrigEspecial", 49.50, "Grande", 5);

INSERT INTO tb_pizzas (sabor, nome, preco, tipo,  tb_categorias_id)
VALUE ("Nutella", "Nuteprime", 99.99, "Grande", 1);

-- Retorno de dados da tabela pizzas
SELECT * FROM tb_pizzas WHERE preco > 45;
SELECT * FROM tb_pizzas WHERE preco BETWEEN 50 AND 100;

SELECT * FROM tb_pizzas WHERE nome LIKE "%m%";

SELECT * FROM tb_pizzas INNER JOIN tb_categorias
ON tb_pizzas.tb_categorias_id = tb_categorias.id;

SELECT sabor, tb_categorias.pizza_doce FROM tb_pizzas
INNER JOIN tb_categorias ON tb_pizzas.tb_categorias_id = tb_categorias.id
WHERE tb_categorias.pizza_doce = "Prime doce";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;